spring:
  application:
    # 服务名称
    name: blog-feign
  cloud:
    nacos:
      config:
        server-addr: 192.168.100.130:8848
        file-extension: yaml
        namespace: bb8c61ad-dfed-47d6-a37d-fe5af5d69b6d
        refresh-enabled: true
      discovery:
        server-addr: 192.168.100.130:8848
  config:
    import: nacos:${spring.application.name}


